services:
  - type: web
    name: notes-copilot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: EMBED_PROVIDER
        value: gemini
      - key: EMBED_MODEL
        value: text-embedding-004
      - key: EMBED_DIM
        value: "768"
      - key: FRONTEND_ORIGIN
        value: https://<your-vercel-app>.vercel.app
